### ISSUE TITLE
`Delimiter` keyword support

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-database-client#3]
Can u add support for the `delimiter` keyword to support modifying stored procs?  The other MySql plugin supports it (https://marketplace.visualstudio.com/items?itemName=poreklo.vscode-mysql)

**Comment by cweijan** [comment]
you  can modify stored proc directly without delimiter.

**Comment by silverbullettruck2001** [comment]
I see that I don't need to have it, but I also would like the option to specify it as our company requires that we include it in our deployed scripts.  This is because it is required by some of our deployment tooling.

**Comment by silverbullettruck2001** [comment]
@cweijan is there any way that this could be added?  It would really help since it is supported mySQL syntax.

**Comment by cweijan** [comment]
I think the delimiter is useless. so not enthusiasm for development it, If you give this project a star, I can implement it for you.

**Comment by silverbullettruck2001** [comment]
I gave it a star!  It's definitely worth it!  Thanks for implementing this for me!

**Comment by cweijan** [comment]
version 1.9.0 is add delimiter feature, Note that it is not stable.
You need config setting.
`"vscode-mysql.enableDelimiter": true`

**Comment by silverbullettruck2001** [comment]
That sounds like great progress!  Could you explain what is "not stable" about the build?

**Comment by cweijan** [comment]
If you batch run sql with delimiter, that will be no problem.

But after run one line sql like `delimiter $$`, the intelli sql edit maybe loss effectiveness.

**Comment by silverbullettruck2001** [comment]
@cweijan When I try to use this I still get an error.  Here's the test script I was trying to run just to try out the functionality:

delimiter ~
drop procedure if exists `test`~
create procedure `test`()
begin
  select 1;
end~
delimiter ;

I just pasted that in a query window, made sure I had an active connection and a database specified.  I verified that I had the `Vscode-mysql:Enable Delimiter` setting checked on the Right clicked and chose 'Run MySQL Query' and this is the error returned:

```
EXECUTE FAIL:

  delimiter ~ drop procedure if exists `test`~ create procedure `test` begin select 1; end~ 

Message :

  ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'delimiter ~ drop procedure if exists `test`~ create procedure `test` begin sel' at line 1
```

Is there something I am not doing correctly?  I am on version 1.9.7

**Comment by cweijan** [comment]
~ is not support, new version is fixed, 
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2&ssr=false#overview

**Comment by silverbullettruck2001** [comment]
@cweijan I upgraded to 2.1.1 and it works better, but there is still an issue.  When I run the above command I get a message saying it ran successfully, but then stops being responsive.  There is an animation on the screen that say "Loading Data" which it does for a few seconds and then over in the left hand navigation window where it says "MYSQL:MYSQL" there is a blue scroller that just keeps circling and as well as a blue clock over the database icon.  Until it stops circling and the clock goes away I cannot issue any other commands to the database.  There's no indication on why this is happening.  Any thoughts?  

Also, I want to say thanks again for working on this!  I really hope that these issues can be overcome and make this even better!  Thanks again!

**Comment by silverbullettruck2001** [comment]
@cweijan do you have a way to resolve this?

**Comment by cweijan** [comment]
I run this SQL, it works normally.. How to reproduce your problem?
```SQL
delimiter ~
drop procedure if exists test~
create procedure test()
begin
select 1;
end~
delimiter ;
```

**Comment by silverbullettruck2001** [comment]
I just updated to 2.1.4 and this is still occurring.  All I do is right click on the screen, choose 'Run MySQL Query' and it runs successfully, but the connection seems to hang.  There are rotating dot circle next to the database icon in the list of databases as well as the left navigation.  I am not sure what other details to provide as it does it consistently for me, so I am not sure why it doesn't do it for you.  Here is a link to a screenshot so you can see what I am getting:

[screenshot](https://paste.pics/431bc1a9184bf6824e71dff1cf06bd34)

**Comment by cweijan** [comment]
Sorry, I still cannot reproduce the error
The circle block occur in [this](https://github.com/cweijan/vscode-mysql/blob/ae563ce282daeec5037270aacbd9e9630226688f/src/model/database/connectionNode.ts#L26), maybe you can try to debug the program

**Comment by cweijan** [comment]
I think I have located this bug, update to 2.1.9 to try, @silverbullettruck2001

**Comment by silverbullettruck2001** [comment]
Thanks I will definitely give this a shot!  Thanks!

**Comment by silverbullettruck2001** [comment]
@cweijan, it works a little better.  Now when I execute the statement it works fine the first time, but if I execute the same script a second time it does the same thing as before where it hangs for a long period of time.  Any idea if that can be addressed?

**Comment by kBondarchuk** [comment]
I use **DELIMITER $$** and it works fine. But if I have some text selected in editor it trying to run selected text only and gives erros. It's annoying.
